# Generated by Django 3.2.12 on 2023-05-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_create_product_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='additional_payment_price',
            field=models.IntegerField(db_index=True, verbose_name='추가 판매가'),
        ),
    ]
