# Generated by Django 3.2.12 on 2023-05-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productitem_additional_payment_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productiteminfo',
            unique_together={('product_item', 'product_item_info_type')},
        ),
    ]
