# Generated by Django 3.2.12 on 2023-05-29 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepopupmodal',
            old_name='on_clicK_link',
            new_name='on_click_link',
        ),
    ]
