# Generated by Django 3.2.12 on 2023-05-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0003_auto_20230529_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepopupmodal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='homepopupmodal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 시간'),
        ),
    ]
