# Generated by Django 3.2.12 on 2023-05-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0004_auto_20230529_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepopupmodal',
            name='sequence',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text='숫자가 작을수록 앞에 있음', verbose_name='앞에 있는 순서'),
        ),
    ]
