# Generated by Django 3.2.12 on 2023-05-29 11:25

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='종료 시간')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('description', models.TextField(blank=True, null=True, verbose_name='관리자 보기 위한 설명')),
                ('image', models.TextField(blank=True, null=True, verbose_name='이미지')),
                ('on_click_link', models.TextField(null=True, verbose_name='클릭 시 링크')),
                ('sequence', models.PositiveIntegerField(db_index=True, default=1, help_text='숫자가 작을수록 앞에 있음', verbose_name='순서')),
            ],
            options={
                'verbose_name': '배너',
                'verbose_name_plural': '배너',
            },
            managers=[
                ('datetime_active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
